package com.hsl.crawler.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PositionExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table position
	 * @mbggenerated  Sun Jun 02 14:07:59 CST 2019
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table position
	 * @mbggenerated  Sun Jun 02 14:07:59 CST 2019
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table position
	 * @mbggenerated  Sun Jun 02 14:07:59 CST 2019
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table position
	 * @mbggenerated  Sun Jun 02 14:07:59 CST 2019
	 */
	public PositionExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table position
	 * @mbggenerated  Sun Jun 02 14:07:59 CST 2019
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table position
	 * @mbggenerated  Sun Jun 02 14:07:59 CST 2019
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table position
	 * @mbggenerated  Sun Jun 02 14:07:59 CST 2019
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table position
	 * @mbggenerated  Sun Jun 02 14:07:59 CST 2019
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table position
	 * @mbggenerated  Sun Jun 02 14:07:59 CST 2019
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table position
	 * @mbggenerated  Sun Jun 02 14:07:59 CST 2019
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table position
	 * @mbggenerated  Sun Jun 02 14:07:59 CST 2019
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table position
	 * @mbggenerated  Sun Jun 02 14:07:59 CST 2019
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table position
	 * @mbggenerated  Sun Jun 02 14:07:59 CST 2019
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table position
	 * @mbggenerated  Sun Jun 02 14:07:59 CST 2019
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table position
	 * @mbggenerated  Sun Jun 02 14:07:59 CST 2019
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andPositidIsNull() {
			addCriterion("positId is null");
			return (Criteria) this;
		}

		public Criteria andPositidIsNotNull() {
			addCriterion("positId is not null");
			return (Criteria) this;
		}

		public Criteria andPositidEqualTo(Integer value) {
			addCriterion("positId =", value, "positid");
			return (Criteria) this;
		}

		public Criteria andPositidNotEqualTo(Integer value) {
			addCriterion("positId <>", value, "positid");
			return (Criteria) this;
		}

		public Criteria andPositidGreaterThan(Integer value) {
			addCriterion("positId >", value, "positid");
			return (Criteria) this;
		}

		public Criteria andPositidGreaterThanOrEqualTo(Integer value) {
			addCriterion("positId >=", value, "positid");
			return (Criteria) this;
		}

		public Criteria andPositidLessThan(Integer value) {
			addCriterion("positId <", value, "positid");
			return (Criteria) this;
		}

		public Criteria andPositidLessThanOrEqualTo(Integer value) {
			addCriterion("positId <=", value, "positid");
			return (Criteria) this;
		}

		public Criteria andPositidIn(List<Integer> values) {
			addCriterion("positId in", values, "positid");
			return (Criteria) this;
		}

		public Criteria andPositidNotIn(List<Integer> values) {
			addCriterion("positId not in", values, "positid");
			return (Criteria) this;
		}

		public Criteria andPositidBetween(Integer value1, Integer value2) {
			addCriterion("positId between", value1, value2, "positid");
			return (Criteria) this;
		}

		public Criteria andPositidNotBetween(Integer value1, Integer value2) {
			addCriterion("positId not between", value1, value2, "positid");
			return (Criteria) this;
		}

		public Criteria andPageidIsNull() {
			addCriterion("pageId is null");
			return (Criteria) this;
		}

		public Criteria andPageidIsNotNull() {
			addCriterion("pageId is not null");
			return (Criteria) this;
		}

		public Criteria andPageidEqualTo(Integer value) {
			addCriterion("pageId =", value, "pageid");
			return (Criteria) this;
		}

		public Criteria andPageidNotEqualTo(Integer value) {
			addCriterion("pageId <>", value, "pageid");
			return (Criteria) this;
		}

		public Criteria andPageidGreaterThan(Integer value) {
			addCriterion("pageId >", value, "pageid");
			return (Criteria) this;
		}

		public Criteria andPageidGreaterThanOrEqualTo(Integer value) {
			addCriterion("pageId >=", value, "pageid");
			return (Criteria) this;
		}

		public Criteria andPageidLessThan(Integer value) {
			addCriterion("pageId <", value, "pageid");
			return (Criteria) this;
		}

		public Criteria andPageidLessThanOrEqualTo(Integer value) {
			addCriterion("pageId <=", value, "pageid");
			return (Criteria) this;
		}

		public Criteria andPageidIn(List<Integer> values) {
			addCriterion("pageId in", values, "pageid");
			return (Criteria) this;
		}

		public Criteria andPageidNotIn(List<Integer> values) {
			addCriterion("pageId not in", values, "pageid");
			return (Criteria) this;
		}

		public Criteria andPageidBetween(Integer value1, Integer value2) {
			addCriterion("pageId between", value1, value2, "pageid");
			return (Criteria) this;
		}

		public Criteria andPageidNotBetween(Integer value1, Integer value2) {
			addCriterion("pageId not between", value1, value2, "pageid");
			return (Criteria) this;
		}

		public Criteria andCompanyfullnameIsNull() {
			addCriterion("companyFullName is null");
			return (Criteria) this;
		}

		public Criteria andCompanyfullnameIsNotNull() {
			addCriterion("companyFullName is not null");
			return (Criteria) this;
		}

		public Criteria andCompanyfullnameEqualTo(String value) {
			addCriterion("companyFullName =", value, "companyfullname");
			return (Criteria) this;
		}

		public Criteria andCompanyfullnameNotEqualTo(String value) {
			addCriterion("companyFullName <>", value, "companyfullname");
			return (Criteria) this;
		}

		public Criteria andCompanyfullnameGreaterThan(String value) {
			addCriterion("companyFullName >", value, "companyfullname");
			return (Criteria) this;
		}

		public Criteria andCompanyfullnameGreaterThanOrEqualTo(String value) {
			addCriterion("companyFullName >=", value, "companyfullname");
			return (Criteria) this;
		}

		public Criteria andCompanyfullnameLessThan(String value) {
			addCriterion("companyFullName <", value, "companyfullname");
			return (Criteria) this;
		}

		public Criteria andCompanyfullnameLessThanOrEqualTo(String value) {
			addCriterion("companyFullName <=", value, "companyfullname");
			return (Criteria) this;
		}

		public Criteria andCompanyfullnameLike(String value) {
			addCriterion("companyFullName like", value, "companyfullname");
			return (Criteria) this;
		}

		public Criteria andCompanyfullnameNotLike(String value) {
			addCriterion("companyFullName not like", value, "companyfullname");
			return (Criteria) this;
		}

		public Criteria andCompanyfullnameIn(List<String> values) {
			addCriterion("companyFullName in", values, "companyfullname");
			return (Criteria) this;
		}

		public Criteria andCompanyfullnameNotIn(List<String> values) {
			addCriterion("companyFullName not in", values, "companyfullname");
			return (Criteria) this;
		}

		public Criteria andCompanyfullnameBetween(String value1, String value2) {
			addCriterion("companyFullName between", value1, value2,
					"companyfullname");
			return (Criteria) this;
		}

		public Criteria andCompanyfullnameNotBetween(String value1,
				String value2) {
			addCriterion("companyFullName not between", value1, value2,
					"companyfullname");
			return (Criteria) this;
		}

		public Criteria andCompanyshortnameIsNull() {
			addCriterion("companyShortName is null");
			return (Criteria) this;
		}

		public Criteria andCompanyshortnameIsNotNull() {
			addCriterion("companyShortName is not null");
			return (Criteria) this;
		}

		public Criteria andCompanyshortnameEqualTo(String value) {
			addCriterion("companyShortName =", value, "companyshortname");
			return (Criteria) this;
		}

		public Criteria andCompanyshortnameNotEqualTo(String value) {
			addCriterion("companyShortName <>", value, "companyshortname");
			return (Criteria) this;
		}

		public Criteria andCompanyshortnameGreaterThan(String value) {
			addCriterion("companyShortName >", value, "companyshortname");
			return (Criteria) this;
		}

		public Criteria andCompanyshortnameGreaterThanOrEqualTo(String value) {
			addCriterion("companyShortName >=", value, "companyshortname");
			return (Criteria) this;
		}

		public Criteria andCompanyshortnameLessThan(String value) {
			addCriterion("companyShortName <", value, "companyshortname");
			return (Criteria) this;
		}

		public Criteria andCompanyshortnameLessThanOrEqualTo(String value) {
			addCriterion("companyShortName <=", value, "companyshortname");
			return (Criteria) this;
		}

		public Criteria andCompanyshortnameLike(String value) {
			addCriterion("companyShortName like", value, "companyshortname");
			return (Criteria) this;
		}

		public Criteria andCompanyshortnameNotLike(String value) {
			addCriterion("companyShortName not like", value, "companyshortname");
			return (Criteria) this;
		}

		public Criteria andCompanyshortnameIn(List<String> values) {
			addCriterion("companyShortName in", values, "companyshortname");
			return (Criteria) this;
		}

		public Criteria andCompanyshortnameNotIn(List<String> values) {
			addCriterion("companyShortName not in", values, "companyshortname");
			return (Criteria) this;
		}

		public Criteria andCompanyshortnameBetween(String value1, String value2) {
			addCriterion("companyShortName between", value1, value2,
					"companyshortname");
			return (Criteria) this;
		}

		public Criteria andCompanyshortnameNotBetween(String value1,
				String value2) {
			addCriterion("companyShortName not between", value1, value2,
					"companyshortname");
			return (Criteria) this;
		}

		public Criteria andCompanysizeIsNull() {
			addCriterion("companySize is null");
			return (Criteria) this;
		}

		public Criteria andCompanysizeIsNotNull() {
			addCriterion("companySize is not null");
			return (Criteria) this;
		}

		public Criteria andCompanysizeEqualTo(String value) {
			addCriterion("companySize =", value, "companysize");
			return (Criteria) this;
		}

		public Criteria andCompanysizeNotEqualTo(String value) {
			addCriterion("companySize <>", value, "companysize");
			return (Criteria) this;
		}

		public Criteria andCompanysizeGreaterThan(String value) {
			addCriterion("companySize >", value, "companysize");
			return (Criteria) this;
		}

		public Criteria andCompanysizeGreaterThanOrEqualTo(String value) {
			addCriterion("companySize >=", value, "companysize");
			return (Criteria) this;
		}

		public Criteria andCompanysizeLessThan(String value) {
			addCriterion("companySize <", value, "companysize");
			return (Criteria) this;
		}

		public Criteria andCompanysizeLessThanOrEqualTo(String value) {
			addCriterion("companySize <=", value, "companysize");
			return (Criteria) this;
		}

		public Criteria andCompanysizeLike(String value) {
			addCriterion("companySize like", value, "companysize");
			return (Criteria) this;
		}

		public Criteria andCompanysizeNotLike(String value) {
			addCriterion("companySize not like", value, "companysize");
			return (Criteria) this;
		}

		public Criteria andCompanysizeIn(List<String> values) {
			addCriterion("companySize in", values, "companysize");
			return (Criteria) this;
		}

		public Criteria andCompanysizeNotIn(List<String> values) {
			addCriterion("companySize not in", values, "companysize");
			return (Criteria) this;
		}

		public Criteria andCompanysizeBetween(String value1, String value2) {
			addCriterion("companySize between", value1, value2, "companysize");
			return (Criteria) this;
		}

		public Criteria andCompanysizeNotBetween(String value1, String value2) {
			addCriterion("companySize not between", value1, value2,
					"companysize");
			return (Criteria) this;
		}

		public Criteria andFinancestageIsNull() {
			addCriterion("financeStage is null");
			return (Criteria) this;
		}

		public Criteria andFinancestageIsNotNull() {
			addCriterion("financeStage is not null");
			return (Criteria) this;
		}

		public Criteria andFinancestageEqualTo(String value) {
			addCriterion("financeStage =", value, "financestage");
			return (Criteria) this;
		}

		public Criteria andFinancestageNotEqualTo(String value) {
			addCriterion("financeStage <>", value, "financestage");
			return (Criteria) this;
		}

		public Criteria andFinancestageGreaterThan(String value) {
			addCriterion("financeStage >", value, "financestage");
			return (Criteria) this;
		}

		public Criteria andFinancestageGreaterThanOrEqualTo(String value) {
			addCriterion("financeStage >=", value, "financestage");
			return (Criteria) this;
		}

		public Criteria andFinancestageLessThan(String value) {
			addCriterion("financeStage <", value, "financestage");
			return (Criteria) this;
		}

		public Criteria andFinancestageLessThanOrEqualTo(String value) {
			addCriterion("financeStage <=", value, "financestage");
			return (Criteria) this;
		}

		public Criteria andFinancestageLike(String value) {
			addCriterion("financeStage like", value, "financestage");
			return (Criteria) this;
		}

		public Criteria andFinancestageNotLike(String value) {
			addCriterion("financeStage not like", value, "financestage");
			return (Criteria) this;
		}

		public Criteria andFinancestageIn(List<String> values) {
			addCriterion("financeStage in", values, "financestage");
			return (Criteria) this;
		}

		public Criteria andFinancestageNotIn(List<String> values) {
			addCriterion("financeStage not in", values, "financestage");
			return (Criteria) this;
		}

		public Criteria andFinancestageBetween(String value1, String value2) {
			addCriterion("financeStage between", value1, value2, "financestage");
			return (Criteria) this;
		}

		public Criteria andFinancestageNotBetween(String value1, String value2) {
			addCriterion("financeStage not between", value1, value2,
					"financestage");
			return (Criteria) this;
		}

		public Criteria andCompanyidIsNull() {
			addCriterion("companyId is null");
			return (Criteria) this;
		}

		public Criteria andCompanyidIsNotNull() {
			addCriterion("companyId is not null");
			return (Criteria) this;
		}

		public Criteria andCompanyidEqualTo(String value) {
			addCriterion("companyId =", value, "companyid");
			return (Criteria) this;
		}

		public Criteria andCompanyidNotEqualTo(String value) {
			addCriterion("companyId <>", value, "companyid");
			return (Criteria) this;
		}

		public Criteria andCompanyidGreaterThan(String value) {
			addCriterion("companyId >", value, "companyid");
			return (Criteria) this;
		}

		public Criteria andCompanyidGreaterThanOrEqualTo(String value) {
			addCriterion("companyId >=", value, "companyid");
			return (Criteria) this;
		}

		public Criteria andCompanyidLessThan(String value) {
			addCriterion("companyId <", value, "companyid");
			return (Criteria) this;
		}

		public Criteria andCompanyidLessThanOrEqualTo(String value) {
			addCriterion("companyId <=", value, "companyid");
			return (Criteria) this;
		}

		public Criteria andCompanyidLike(String value) {
			addCriterion("companyId like", value, "companyid");
			return (Criteria) this;
		}

		public Criteria andCompanyidNotLike(String value) {
			addCriterion("companyId not like", value, "companyid");
			return (Criteria) this;
		}

		public Criteria andCompanyidIn(List<String> values) {
			addCriterion("companyId in", values, "companyid");
			return (Criteria) this;
		}

		public Criteria andCompanyidNotIn(List<String> values) {
			addCriterion("companyId not in", values, "companyid");
			return (Criteria) this;
		}

		public Criteria andCompanyidBetween(String value1, String value2) {
			addCriterion("companyId between", value1, value2, "companyid");
			return (Criteria) this;
		}

		public Criteria andCompanyidNotBetween(String value1, String value2) {
			addCriterion("companyId not between", value1, value2, "companyid");
			return (Criteria) this;
		}

		public Criteria andPositionidIsNull() {
			addCriterion("positionId is null");
			return (Criteria) this;
		}

		public Criteria andPositionidIsNotNull() {
			addCriterion("positionId is not null");
			return (Criteria) this;
		}

		public Criteria andPositionidEqualTo(String value) {
			addCriterion("positionId =", value, "positionid");
			return (Criteria) this;
		}

		public Criteria andPositionidNotEqualTo(String value) {
			addCriterion("positionId <>", value, "positionid");
			return (Criteria) this;
		}

		public Criteria andPositionidGreaterThan(String value) {
			addCriterion("positionId >", value, "positionid");
			return (Criteria) this;
		}

		public Criteria andPositionidGreaterThanOrEqualTo(String value) {
			addCriterion("positionId >=", value, "positionid");
			return (Criteria) this;
		}

		public Criteria andPositionidLessThan(String value) {
			addCriterion("positionId <", value, "positionid");
			return (Criteria) this;
		}

		public Criteria andPositionidLessThanOrEqualTo(String value) {
			addCriterion("positionId <=", value, "positionid");
			return (Criteria) this;
		}

		public Criteria andPositionidLike(String value) {
			addCriterion("positionId like", value, "positionid");
			return (Criteria) this;
		}

		public Criteria andPositionidNotLike(String value) {
			addCriterion("positionId not like", value, "positionid");
			return (Criteria) this;
		}

		public Criteria andPositionidIn(List<String> values) {
			addCriterion("positionId in", values, "positionid");
			return (Criteria) this;
		}

		public Criteria andPositionidNotIn(List<String> values) {
			addCriterion("positionId not in", values, "positionid");
			return (Criteria) this;
		}

		public Criteria andPositionidBetween(String value1, String value2) {
			addCriterion("positionId between", value1, value2, "positionid");
			return (Criteria) this;
		}

		public Criteria andPositionidNotBetween(String value1, String value2) {
			addCriterion("positionId not between", value1, value2, "positionid");
			return (Criteria) this;
		}

		public Criteria andCityIsNull() {
			addCriterion("city is null");
			return (Criteria) this;
		}

		public Criteria andCityIsNotNull() {
			addCriterion("city is not null");
			return (Criteria) this;
		}

		public Criteria andCityEqualTo(String value) {
			addCriterion("city =", value, "city");
			return (Criteria) this;
		}

		public Criteria andCityNotEqualTo(String value) {
			addCriterion("city <>", value, "city");
			return (Criteria) this;
		}

		public Criteria andCityGreaterThan(String value) {
			addCriterion("city >", value, "city");
			return (Criteria) this;
		}

		public Criteria andCityGreaterThanOrEqualTo(String value) {
			addCriterion("city >=", value, "city");
			return (Criteria) this;
		}

		public Criteria andCityLessThan(String value) {
			addCriterion("city <", value, "city");
			return (Criteria) this;
		}

		public Criteria andCityLessThanOrEqualTo(String value) {
			addCriterion("city <=", value, "city");
			return (Criteria) this;
		}

		public Criteria andCityLike(String value) {
			addCriterion("city like", value, "city");
			return (Criteria) this;
		}

		public Criteria andCityNotLike(String value) {
			addCriterion("city not like", value, "city");
			return (Criteria) this;
		}

		public Criteria andCityIn(List<String> values) {
			addCriterion("city in", values, "city");
			return (Criteria) this;
		}

		public Criteria andCityNotIn(List<String> values) {
			addCriterion("city not in", values, "city");
			return (Criteria) this;
		}

		public Criteria andCityBetween(String value1, String value2) {
			addCriterion("city between", value1, value2, "city");
			return (Criteria) this;
		}

		public Criteria andCityNotBetween(String value1, String value2) {
			addCriterion("city not between", value1, value2, "city");
			return (Criteria) this;
		}

		public Criteria andUrlIsNull() {
			addCriterion("url is null");
			return (Criteria) this;
		}

		public Criteria andUrlIsNotNull() {
			addCriterion("url is not null");
			return (Criteria) this;
		}

		public Criteria andUrlEqualTo(String value) {
			addCriterion("url =", value, "url");
			return (Criteria) this;
		}

		public Criteria andUrlNotEqualTo(String value) {
			addCriterion("url <>", value, "url");
			return (Criteria) this;
		}

		public Criteria andUrlGreaterThan(String value) {
			addCriterion("url >", value, "url");
			return (Criteria) this;
		}

		public Criteria andUrlGreaterThanOrEqualTo(String value) {
			addCriterion("url >=", value, "url");
			return (Criteria) this;
		}

		public Criteria andUrlLessThan(String value) {
			addCriterion("url <", value, "url");
			return (Criteria) this;
		}

		public Criteria andUrlLessThanOrEqualTo(String value) {
			addCriterion("url <=", value, "url");
			return (Criteria) this;
		}

		public Criteria andUrlLike(String value) {
			addCriterion("url like", value, "url");
			return (Criteria) this;
		}

		public Criteria andUrlNotLike(String value) {
			addCriterion("url not like", value, "url");
			return (Criteria) this;
		}

		public Criteria andUrlIn(List<String> values) {
			addCriterion("url in", values, "url");
			return (Criteria) this;
		}

		public Criteria andUrlNotIn(List<String> values) {
			addCriterion("url not in", values, "url");
			return (Criteria) this;
		}

		public Criteria andUrlBetween(String value1, String value2) {
			addCriterion("url between", value1, value2, "url");
			return (Criteria) this;
		}

		public Criteria andUrlNotBetween(String value1, String value2) {
			addCriterion("url not between", value1, value2, "url");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("status is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("status is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(Integer value) {
			addCriterion("status =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(Integer value) {
			addCriterion("status <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(Integer value) {
			addCriterion("status >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
			addCriterion("status >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(Integer value) {
			addCriterion("status <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(Integer value) {
			addCriterion("status <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<Integer> values) {
			addCriterion("status in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<Integer> values) {
			addCriterion("status not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(Integer value1, Integer value2) {
			addCriterion("status between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(Integer value1, Integer value2) {
			addCriterion("status not between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andDescriptionIsNull() {
			addCriterion("description is null");
			return (Criteria) this;
		}

		public Criteria andDescriptionIsNotNull() {
			addCriterion("description is not null");
			return (Criteria) this;
		}

		public Criteria andDescriptionEqualTo(String value) {
			addCriterion("description =", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotEqualTo(String value) {
			addCriterion("description <>", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionGreaterThan(String value) {
			addCriterion("description >", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
			addCriterion("description >=", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionLessThan(String value) {
			addCriterion("description <", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionLessThanOrEqualTo(String value) {
			addCriterion("description <=", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionLike(String value) {
			addCriterion("description like", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotLike(String value) {
			addCriterion("description not like", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionIn(List<String> values) {
			addCriterion("description in", values, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotIn(List<String> values) {
			addCriterion("description not in", values, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionBetween(String value1, String value2) {
			addCriterion("description between", value1, value2, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotBetween(String value1, String value2) {
			addCriterion("description not between", value1, value2,
					"description");
			return (Criteria) this;
		}

		public Criteria andTimeIsNull() {
			addCriterion("time is null");
			return (Criteria) this;
		}

		public Criteria andTimeIsNotNull() {
			addCriterion("time is not null");
			return (Criteria) this;
		}

		public Criteria andTimeEqualTo(Date value) {
			addCriterion("time =", value, "time");
			return (Criteria) this;
		}

		public Criteria andTimeNotEqualTo(Date value) {
			addCriterion("time <>", value, "time");
			return (Criteria) this;
		}

		public Criteria andTimeGreaterThan(Date value) {
			addCriterion("time >", value, "time");
			return (Criteria) this;
		}

		public Criteria andTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("time >=", value, "time");
			return (Criteria) this;
		}

		public Criteria andTimeLessThan(Date value) {
			addCriterion("time <", value, "time");
			return (Criteria) this;
		}

		public Criteria andTimeLessThanOrEqualTo(Date value) {
			addCriterion("time <=", value, "time");
			return (Criteria) this;
		}

		public Criteria andTimeIn(List<Date> values) {
			addCriterion("time in", values, "time");
			return (Criteria) this;
		}

		public Criteria andTimeNotIn(List<Date> values) {
			addCriterion("time not in", values, "time");
			return (Criteria) this;
		}

		public Criteria andTimeBetween(Date value1, Date value2) {
			addCriterion("time between", value1, value2, "time");
			return (Criteria) this;
		}

		public Criteria andTimeNotBetween(Date value1, Date value2) {
			addCriterion("time not between", value1, value2, "time");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table position
	 * @mbggenerated  Sun Jun 02 14:07:59 CST 2019
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table position
     *
     * @mbggenerated do_not_delete_during_merge Fri May 31 16:36:05 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}