package com.hsl.crawler.entity;

import java.util.Date;

public class Position {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column position.positId
	 * @mbggenerated  Sun Jun 02 14:07:59 CST 2019
	 */
	private Integer positid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column position.pageId
	 * @mbggenerated  Sun Jun 02 14:07:59 CST 2019
	 */
	private Integer pageid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column position.companyFullName
	 * @mbggenerated  Sun Jun 02 14:07:59 CST 2019
	 */
	private String companyfullname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column position.companyShortName
	 * @mbggenerated  Sun Jun 02 14:07:59 CST 2019
	 */
	private String companyshortname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column position.companySize
	 * @mbggenerated  Sun Jun 02 14:07:59 CST 2019
	 */
	private String companysize;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column position.financeStage
	 * @mbggenerated  Sun Jun 02 14:07:59 CST 2019
	 */
	private String financestage;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column position.companyId
	 * @mbggenerated  Sun Jun 02 14:07:59 CST 2019
	 */
	private String companyid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column position.positionId
	 * @mbggenerated  Sun Jun 02 14:07:59 CST 2019
	 */
	private String positionid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column position.city
	 * @mbggenerated  Sun Jun 02 14:07:59 CST 2019
	 */
	private String city;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column position.url
	 * @mbggenerated  Sun Jun 02 14:07:59 CST 2019
	 */
	private String url;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column position.status
	 * @mbggenerated  Sun Jun 02 14:07:59 CST 2019
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column position.description
	 * @mbggenerated  Sun Jun 02 14:07:59 CST 2019
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column position.time
	 * @mbggenerated  Sun Jun 02 14:07:59 CST 2019
	 */
	private Date time;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column position.positId
	 * @return  the value of position.positId
	 * @mbggenerated  Sun Jun 02 14:07:59 CST 2019
	 */
	public Integer getPositid() {
		return positid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column position.positId
	 * @param positid  the value for position.positId
	 * @mbggenerated  Sun Jun 02 14:07:59 CST 2019
	 */
	public void setPositid(Integer positid) {
		this.positid = positid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column position.pageId
	 * @return  the value of position.pageId
	 * @mbggenerated  Sun Jun 02 14:07:59 CST 2019
	 */
	public Integer getPageid() {
		return pageid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column position.pageId
	 * @param pageid  the value for position.pageId
	 * @mbggenerated  Sun Jun 02 14:07:59 CST 2019
	 */
	public void setPageid(Integer pageid) {
		this.pageid = pageid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column position.companyFullName
	 * @return  the value of position.companyFullName
	 * @mbggenerated  Sun Jun 02 14:07:59 CST 2019
	 */
	public String getCompanyfullname() {
		return companyfullname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column position.companyFullName
	 * @param companyfullname  the value for position.companyFullName
	 * @mbggenerated  Sun Jun 02 14:07:59 CST 2019
	 */
	public void setCompanyfullname(String companyfullname) {
		this.companyfullname = companyfullname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column position.companyShortName
	 * @return  the value of position.companyShortName
	 * @mbggenerated  Sun Jun 02 14:07:59 CST 2019
	 */
	public String getCompanyshortname() {
		return companyshortname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column position.companyShortName
	 * @param companyshortname  the value for position.companyShortName
	 * @mbggenerated  Sun Jun 02 14:07:59 CST 2019
	 */
	public void setCompanyshortname(String companyshortname) {
		this.companyshortname = companyshortname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column position.companySize
	 * @return  the value of position.companySize
	 * @mbggenerated  Sun Jun 02 14:07:59 CST 2019
	 */
	public String getCompanysize() {
		return companysize;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column position.companySize
	 * @param companysize  the value for position.companySize
	 * @mbggenerated  Sun Jun 02 14:07:59 CST 2019
	 */
	public void setCompanysize(String companysize) {
		this.companysize = companysize;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column position.financeStage
	 * @return  the value of position.financeStage
	 * @mbggenerated  Sun Jun 02 14:07:59 CST 2019
	 */
	public String getFinancestage() {
		return financestage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column position.financeStage
	 * @param financestage  the value for position.financeStage
	 * @mbggenerated  Sun Jun 02 14:07:59 CST 2019
	 */
	public void setFinancestage(String financestage) {
		this.financestage = financestage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column position.companyId
	 * @return  the value of position.companyId
	 * @mbggenerated  Sun Jun 02 14:07:59 CST 2019
	 */
	public String getCompanyid() {
		return companyid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column position.companyId
	 * @param companyid  the value for position.companyId
	 * @mbggenerated  Sun Jun 02 14:07:59 CST 2019
	 */
	public void setCompanyid(String companyid) {
		this.companyid = companyid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column position.positionId
	 * @return  the value of position.positionId
	 * @mbggenerated  Sun Jun 02 14:07:59 CST 2019
	 */
	public String getPositionid() {
		return positionid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column position.positionId
	 * @param positionid  the value for position.positionId
	 * @mbggenerated  Sun Jun 02 14:07:59 CST 2019
	 */
	public void setPositionid(String positionid) {
		this.positionid = positionid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column position.city
	 * @return  the value of position.city
	 * @mbggenerated  Sun Jun 02 14:07:59 CST 2019
	 */
	public String getCity() {
		return city;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column position.city
	 * @param city  the value for position.city
	 * @mbggenerated  Sun Jun 02 14:07:59 CST 2019
	 */
	public void setCity(String city) {
		this.city = city;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column position.url
	 * @return  the value of position.url
	 * @mbggenerated  Sun Jun 02 14:07:59 CST 2019
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column position.url
	 * @param url  the value for position.url
	 * @mbggenerated  Sun Jun 02 14:07:59 CST 2019
	 */
	public void setUrl(String url) {
		this.url = url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column position.status
	 * @return  the value of position.status
	 * @mbggenerated  Sun Jun 02 14:07:59 CST 2019
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column position.status
	 * @param status  the value for position.status
	 * @mbggenerated  Sun Jun 02 14:07:59 CST 2019
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column position.description
	 * @return  the value of position.description
	 * @mbggenerated  Sun Jun 02 14:07:59 CST 2019
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column position.description
	 * @param description  the value for position.description
	 * @mbggenerated  Sun Jun 02 14:07:59 CST 2019
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column position.time
	 * @return  the value of position.time
	 * @mbggenerated  Sun Jun 02 14:07:59 CST 2019
	 */
	public Date getTime() {
		return time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column position.time
	 * @param time  the value for position.time
	 * @mbggenerated  Sun Jun 02 14:07:59 CST 2019
	 */
	public void setTime(Date time) {
		this.time = time;
	}
}