package com.hsl.crawler.entity;

import java.util.Date;

public class Topic {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column topic.topicId
	 * @mbggenerated  Sun Jun 02 14:07:59 CST 2019
	 */
	private Integer topicid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column topic.keyword
	 * @mbggenerated  Sun Jun 02 14:07:59 CST 2019
	 */
	private String keyword;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column topic.url
	 * @mbggenerated  Sun Jun 02 14:07:59 CST 2019
	 */
	private String url;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column topic.status
	 * @mbggenerated  Sun Jun 02 14:07:59 CST 2019
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column topic.time
	 * @mbggenerated  Sun Jun 02 14:07:59 CST 2019
	 */
	private Date time;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column topic.topicId
	 * @return  the value of topic.topicId
	 * @mbggenerated  Sun Jun 02 14:07:59 CST 2019
	 */
	public Integer getTopicid() {
		return topicid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column topic.topicId
	 * @param topicid  the value for topic.topicId
	 * @mbggenerated  Sun Jun 02 14:07:59 CST 2019
	 */
	public void setTopicid(Integer topicid) {
		this.topicid = topicid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column topic.keyword
	 * @return  the value of topic.keyword
	 * @mbggenerated  Sun Jun 02 14:07:59 CST 2019
	 */
	public String getKeyword() {
		return keyword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column topic.keyword
	 * @param keyword  the value for topic.keyword
	 * @mbggenerated  Sun Jun 02 14:07:59 CST 2019
	 */
	public void setKeyword(String keyword) {
		this.keyword = keyword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column topic.url
	 * @return  the value of topic.url
	 * @mbggenerated  Sun Jun 02 14:07:59 CST 2019
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column topic.url
	 * @param url  the value for topic.url
	 * @mbggenerated  Sun Jun 02 14:07:59 CST 2019
	 */
	public void setUrl(String url) {
		this.url = url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column topic.status
	 * @return  the value of topic.status
	 * @mbggenerated  Sun Jun 02 14:07:59 CST 2019
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column topic.status
	 * @param status  the value for topic.status
	 * @mbggenerated  Sun Jun 02 14:07:59 CST 2019
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column topic.time
	 * @return  the value of topic.time
	 * @mbggenerated  Sun Jun 02 14:07:59 CST 2019
	 */
	public Date getTime() {
		return time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column topic.time
	 * @param time  the value for topic.time
	 * @mbggenerated  Sun Jun 02 14:07:59 CST 2019
	 */
	public void setTime(Date time) {
		this.time = time;
	}
}