package com.hsl.crawler.mapper;

import com.hsl.crawler.entity.Page;
import com.hsl.crawler.entity.PageExample;
import java.util.List;

public interface PageMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table page
	 * @mbggenerated  Sun Jun 02 14:07:59 CST 2019
	 */
	int deleteByPrimaryKey(Integer pageid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table page
	 * @mbggenerated  Sun Jun 02 14:07:59 CST 2019
	 */
	int insert(Page record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table page
	 * @mbggenerated  Sun Jun 02 14:07:59 CST 2019
	 */
	int insertSelective(Page record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table page
	 * @mbggenerated  Sun Jun 02 14:07:59 CST 2019
	 */
	List<Page> selectByExampleWithBLOBs(PageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table page
	 * @mbggenerated  Sun Jun 02 14:07:59 CST 2019
	 */
	List<Page> selectByExample(PageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table page
	 * @mbggenerated  Sun Jun 02 14:07:59 CST 2019
	 */
	Page selectByPrimaryKey(Integer pageid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table page
	 * @mbggenerated  Sun Jun 02 14:07:59 CST 2019
	 */
	int updateByPrimaryKeySelective(Page record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table page
	 * @mbggenerated  Sun Jun 02 14:07:59 CST 2019
	 */
	int updateByPrimaryKeyWithBLOBs(Page record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table page
	 * @mbggenerated  Sun Jun 02 14:07:59 CST 2019
	 */
	int updateByPrimaryKey(Page record);
}