package com.hsl.crawler.mapper;

import com.hsl.crawler.entity.Position;
import com.hsl.crawler.entity.PositionExample;
import java.util.List;
import com.hsl.crawler.entity.PositionWithBLOBs;

public interface PositionMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table position
	 * @mbggenerated  Sun Jun 02 14:07:59 CST 2019
	 */
	int deleteByPrimaryKey(Integer positid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table position
	 * @mbggenerated  Sun Jun 02 14:07:59 CST 2019
	 */
	int insert(PositionWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table position
	 * @mbggenerated  Sun Jun 02 14:07:59 CST 2019
	 */
	int insertSelective(PositionWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table position
	 * @mbggenerated  Sun Jun 02 14:07:59 CST 2019
	 */
	List<PositionWithBLOBs> selectByExampleWithBLOBs(PositionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table position
	 * @mbggenerated  Sun Jun 02 14:07:59 CST 2019
	 */
	List<Position> selectByExample(PositionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table position
	 * @mbggenerated  Sun Jun 02 14:07:59 CST 2019
	 */
	PositionWithBLOBs selectByPrimaryKey(Integer positid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table position
	 * @mbggenerated  Sun Jun 02 14:07:59 CST 2019
	 */
	int updateByPrimaryKeySelective(PositionWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table position
	 * @mbggenerated  Sun Jun 02 14:07:59 CST 2019
	 */
	int updateByPrimaryKeyWithBLOBs(PositionWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table position
	 * @mbggenerated  Sun Jun 02 14:07:59 CST 2019
	 */
	int updateByPrimaryKey(Position record);
}