package com.hsl.crawler.mapper;

import com.hsl.crawler.entity.Topic;
import com.hsl.crawler.entity.TopicExample;
import java.util.List;
import com.hsl.crawler.entity.TopicWithBLOBs;

public interface TopicMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table topic
	 * @mbggenerated  Sun Jun 02 14:07:59 CST 2019
	 */
	int deleteByPrimaryKey(Integer topicid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table topic
	 * @mbggenerated  Sun Jun 02 14:07:59 CST 2019
	 */
	int insert(TopicWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table topic
	 * @mbggenerated  Sun Jun 02 14:07:59 CST 2019
	 */
	int insertSelective(TopicWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table topic
	 * @mbggenerated  Sun Jun 02 14:07:59 CST 2019
	 */
	List<TopicWithBLOBs> selectByExampleWithBLOBs(TopicExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table topic
	 * @mbggenerated  Sun Jun 02 14:07:59 CST 2019
	 */
	List<Topic> selectByExample(TopicExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table topic
	 * @mbggenerated  Sun Jun 02 14:07:59 CST 2019
	 */
	TopicWithBLOBs selectByPrimaryKey(Integer topicid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table topic
	 * @mbggenerated  Sun Jun 02 14:07:59 CST 2019
	 */
	int updateByPrimaryKeySelective(TopicWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table topic
	 * @mbggenerated  Sun Jun 02 14:07:59 CST 2019
	 */
	int updateByPrimaryKeyWithBLOBs(TopicWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table topic
	 * @mbggenerated  Sun Jun 02 14:07:59 CST 2019
	 */
	int updateByPrimaryKey(Topic record);
}